version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all

  go:build:
    desc: Build the sleuth binary
    cmds:
      - go build -o bin/sleuth .

  go:run:
    desc: Run the sleuth service locally
    cmds:
      - go run . serve

  go:test:
    desc: Run tests
    cmds:
      - go test -v ./...

  go:test:short:
    desc: Run tests in short mode
    cmds:
      - go test -short -v ./...

  go:test:cover:
    desc: Run tests with coverage
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  go:test:race:
    desc: Run tests with race detection
    cmds:
      - go test -race -v ./...

  go:lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  go:fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  go:vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  go:tidy:
    desc: Download and tidy dependencies
    aliases: [tidy]
    cmds:
      - go mod download
      - go mod tidy

  go:all:
    desc: Run all go lint and test tasks
    cmds:
      - task: go:tidy
      - task: go:fmt
      - task: go:lint
      - task: go:test

  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t sleuth:latest .

  docker:run:
    desc: Run sleuth in Docker
    cmds:
      - docker run -p 8080:8080 sleuth:latest

  specs:generate:
    desc: Generate OpenAPI specifications
    cmds:
      - go run github.com/swaggo/swag/cmd/swag@latest init --generalInfo internal/api/handler.go --output specs/

  client:generate:
    desc: Generate Go client from OpenAPI spec
    cmds:
      - cd client && go generate ./...

  generate:
    desc: Generate OpenAPI specs and client code
    cmds:
      - task: specs:generate
      - task: client:generate

  config:generate:
    desc: Generate a default configuration file
    cmds:
      - mkdir -p config
      - cmd: |
          cat > config/.config.yaml << 'EOF'
          server:
            address: ":8080"
            maxBodySize: 1048576
            scanTimeout: 120s
          scanner:
            dnsTimeout: 10s
            dnsRetries: 3
            httpTimeout: 30s
            maxSubdomains: 50
            subfinderThreads: 10
            maxConcurrency: 5
          intel:
            enabled: true
            feedConfigPath: config/feeds.json
            storageDir: data/intel
            resolverTimeout: 10s
          EOF

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - rm -rf specs/
      - rm -f coverage.out coverage.html

  scan:
    desc: Build container and scan a domain
    deps: [docker:build]
    vars:
      DOMAIN: '{{default "theopenlane.io" .DOMAIN}}'
    cmds:
      - docker run -d --rm -p 8080:8080 --name sleuth-scan sleuth:latest
      - sleep 2
      - >
        curl -s -X POST -H "Content-Type: application/json" -d '{"domain":"{{.DOMAIN}}"}' http://localhost:8080/api/scan
      - docker stop sleuth-scan >/dev/null

  call:health:
    desc: Call the health endpoint
    cmds:
      - curl -s http://localhost:8080/api/health | jq

  call:scan:
    desc: Submit a domain or email to /api/scan
    vars:
      DOMAIN: '{{default "" .DOMAIN}}'
      EMAIL: '{{default "" .EMAIL}}'
    cmds:
      - cmd: >
          ./scripts/scan_submit.sh{{if .DOMAIN}} --domain "{{.DOMAIN}}"{{end}}{{if .EMAIL}} --email "{{.EMAIL}}"{{end}}

  call:intel-hydrate:
    desc: Trigger threat intelligence hydration
    cmds:
      - curl -s -X POST http://localhost:8080/api/intel/hydrate | jq

  call:enrich:
    desc: Enrich a domain or email via Cloudflare Browser Rendering
    vars:
      DOMAIN: '{{default "" .DOMAIN}}'
      EMAIL: '{{default "" .EMAIL}}'
      PORT: '{{default "17710" .PORT}}'
    cmds:
      - cmd: >
          curl -s -X POST -H "Content-Type: application/json"
          -d '{"domain":"{{.DOMAIN}}", "email":"{{.EMAIL}}"}'
          http://localhost:{{.PORT}}/api/enrich | jq

  call:intel-check:
    desc: Score an email/domain against hydrated intel
    vars:
      DOMAIN: '{{default "" .DOMAIN}}'
      EMAIL: '{{default "" .EMAIL}}'
      TYPES: '{{default "" .TYPES}}'
      RESOLVE_IPS: '{{default "false" .RESOLVE_IPS}}'
    cmds:
      - cmd: >
          ./scripts/intel_check.sh{{if .DOMAIN}} --domain "{{.DOMAIN}}"{{end}}{{if .EMAIL}} --email "{{.EMAIL}}"{{end}}{{if .TYPES}} --types "{{.TYPES}}"{{end}} --resolve-ips "{{.RESOLVE_IPS}}"
