version: '3'

includes:
  config:
    taskfile: ./jsonschema/Taskfile.yaml

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all

  go:build:
    desc: Build the sleuth binary
    cmds:
      - go build -o bin/sleuth .

  go:run:
    desc: Run the sleuth service locally
    cmds:
      - go run . serve

  go:test:
    desc: Run tests
    cmds:
      - go test -v ./...

  go:test:short:
    desc: Run tests in short mode
    cmds:
      - go test -short -v ./...

  go:test:cover:
    desc: Run tests with coverage
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  go:test:race:
    desc: Run tests with race detection
    cmds:
      - go test -race -v ./...

  go:lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  go:fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  go:vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  go:tidy:
    desc: Download and tidy dependencies
    aliases: [tidy]
    cmds:
      - go mod download
      - go mod tidy

  go:all:
    desc: Run all go lint and test tasks
    cmds:
      - task: go:tidy
      - task: go:fmt
      - task: go:lint
      - task: go:test

  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t sleuth:latest .

  docker:run:
    desc: Run sleuth in Docker
    cmds:
      - docker run -p 8080:8080 sleuth:latest

  specs:generate:
    desc: Generate OpenAPI specifications
    cmds:
      - go run github.com/swaggo/swag/cmd/swag@latest init --generalInfo internal/api/handler.go --output specs/

  client:generate:
    desc: Generate Go client from OpenAPI spec
    cmds:
      - cd client && go generate ./...

  generate:
    desc: Generate OpenAPI specs and client code
    cmds:
      - task: specs:generate
      - task: client:generate

  config:init:
    desc: Create a local .config.yaml from the example (run config:generate first)
    cmds:
      - cp config/config.example.yaml config/.config.yaml
      - echo "Created config/.config.yaml — edit with your local settings"

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - rm -rf specs/
      - rm -f coverage.out coverage.html

  scan:
    desc: Build container and scan a domain
    deps: ['docker:build']
    vars:
      DOMAIN: '{{default "theopenlane.io" .DOMAIN}}'
    cmds:
      - docker run -d --rm -p 8080:8080 --name sleuth-scan sleuth:latest
      - sleep 2
      - >
        curl -s -X POST -H "Content-Type: application/json" -d '{"domain":"{{.DOMAIN}}"}' http://localhost:8080/api/scan
      - docker stop sleuth-scan >/dev/null

  service:start:
    desc: Build and start the sleuth service in the background
    cmds:
      - task: go:build
      - ./scripts/service_start.sh
      - ./scripts/service_wait.sh

  service:stop:
    desc: Stop the background sleuth service
    cmds:
      - ./scripts/service_stop.sh

  service:logs:
    desc: Tail the background sleuth service logs
    cmds:
      - tail -f .tasktmp/sleuth.log

  ui:
    desc: Rebuild, restart the service, and open the UI in a browser
    cmds:
      - task: service:stop
      - task: service:start
      - open http://localhost:17710/ui

  call:health:
    desc: Call the health endpoint
    cmds:
      - curl -s http://localhost:17710/api/health | jq

  call:scan:
    desc: Submit a domain or email to /api/scan
    vars:
      DOMAIN: '{{default "" .DOMAIN}}'
      EMAIL: '{{default "" .EMAIL}}'
    cmds:
      - cmd: >
          ./scripts/scan_submit.sh{{if .DOMAIN}} --domain "{{.DOMAIN}}"{{end}}{{if .EMAIL}} --email "{{.EMAIL}}"{{end}} #magic___^_^___line
  call:intel-hydrate:
    desc: Trigger threat intelligence hydration
    cmds:
      - curl -s -X POST http://localhost:8080/api/intel/hydrate | jq

  call:enrich:
    desc: Enrich a domain or email via Cloudflare Browser Rendering
    vars:
      DOMAIN: '{{default "" .DOMAIN}}'
      EMAIL: '{{default "" .EMAIL}}'
      PORT: '{{default "17710" .PORT}}'
    cmds:
      - cmd: >
          curl -s -X POST -H "Content-Type: application/json" -d '{"domain":"{{.DOMAIN}}", "email":"{{.EMAIL}}"}' http://localhost:{{.PORT}}/api/enrich | jq #magic___^_^___line
  call:intel-check:
    desc: Score an email/domain against hydrated intel
    vars:
      DOMAIN: '{{default "" .DOMAIN}}'
      EMAIL: '{{default "" .EMAIL}}'
      TYPES: '{{default "" .TYPES}}'
      RESOLVE_IPS: '{{default "false" .RESOLVE_IPS}}'
    cmds:
      - cmd: >
          ./scripts/intel_check.sh{{if .DOMAIN}} --domain "{{.DOMAIN}}"{{end}}{{if .EMAIL}} --email "{{.EMAIL}}"{{end}}{{if .TYPES}} --types "{{.TYPES}}"{{end}} --resolve-ips "{{.RESOLVE_IPS}}" #magic___^_^___line
  call:compliance:
    desc: Discover compliance pages for a domain or email
    vars:
      DOMAIN: '{{default "" .DOMAIN}}'
      EMAIL: '{{default "" .EMAIL}}'
      PORT: '{{default "17710" .PORT}}'
    cmds:
      - cmd: >
          curl -s -X POST -H "Content-Type: application/json" -d '{"domain":"{{.DOMAIN}}", "email":"{{.EMAIL}}"}' http://localhost:{{.PORT}}/api/compliance | jq
  call:all:
    desc: Run health, scan, enrich, and compliance against a domain
    vars:
      DOMAIN: '{{default "theopenlane.io" .DOMAIN}}'
      PORT: '{{default "17710" .PORT}}'
    cmds:
      - echo "--- Health ---"
      - curl -s http://localhost:{{.PORT}}/api/health | jq
      - echo ""
      - echo "--- Scan ---"
      - curl -s -X POST -H "Content-Type:application/json" -d '{"domain":"{{.DOMAIN}}"}' http://localhost:{{.PORT}}/api/scan | jq
      - echo ""
      - echo "--- Compliance ---"
      - curl -s -X POST -H "Content-Type:application/json" -d '{"domain":"{{.DOMAIN}}"}' http://localhost:{{.PORT}}/api/compliance | jq

  precommit-full:
    desc: Lint the project against all files
    cmds:
      - pre-commit install && pre-commit install-hooks
      - pre-commit autoupdate
      - pre-commit run --show-diff-on-failure --color=always --all-files
