env:
  APP_NAME: ${BUILDKITE_PIPELINE_SLUG}
  IMAGE_REPO: ghcr.io/theopenlane/${APP_NAME}
  IMAGE_TAG: ${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_COMMIT:0:8}
  GOFLAGS: -buildvcs=false
  GOCACHE: $HOME/.cache/go-build
  GOMODCACHE: $HOME/.cache/go/pkg/mod
  GOLANGCI_LINT_CACHE: $HOME/.cache/golangci-lint
  HELM_CHART_REPO: git@github.com:theopenlane/openlane-infra.git
  HELM_CHART_PATH: charts/sleuth

secrets:
  - GITHUB_TOKEN
  - SECRET_GHCR_PUBLISH_TOKEN
  - GITHUB_SSH_PRIVATE_KEY

steps:
  - group: ":golangci-lint: Linter"
    key: "linter"
    steps:
      - label: ":golangci-lint: lint :lint-roller:"
        key: "lint"
        cancel_on_build_failing: true
        if: |
          build.message !~ /\[skip ci\]/
        plugins:
          - docker#v5.13.0:
              image: "ghcr.io/theopenlane/build-image:latest"
              always-pull: true
              command: ["task", "go:lint"]
              propagate-environment: true
              volumes:
                - "$GOCACHE:$GOCACHE"
                - "$GOMODCACHE:$GOMODCACHE"
                - "$GOLANGCI_LINT_CACHE:$GOLANGCI_LINT_CACHE"
              environment:
                - "GOTOOLCHAIN=auto"
  - group: ":test_tube: Tests"
    key: "tests"
    steps:
      - label: ":golang: go test"
        key: "go_test"
        cancel_on_build_failing: true
        if: |
          build.message !~ /\[skip ci\]/
        plugins:
          - docker#v5.13.0:
              image: "ghcr.io/theopenlane/build-image:latest"
              always-pull: true
              command: ["task", "go:test"]
              propagate-environment: true
              volumes:
                - "$GOCACHE:$GOCACHE"
                - "$GOMODCACHE:$GOMODCACHE"
              environment:
                - "GOTOOLCHAIN=auto"
  - group: ":golang: Build"
    key: "go-build"
    steps:
      - label: ":golang: build"
        key: "gobuild"
        cancel_on_build_failing: true
        artifact_paths: "bin/${APP_NAME}"
        if: |
          build.message !~ /\[skip ci\]/
        plugins:
          - docker#v5.13.0:
              image: "ghcr.io/theopenlane/build-image:latest"
              always-pull: true
              command: ["task", "go:build"]
              propagate-environment: true
              volumes:
                - "$GOCACHE:$GOCACHE"
                - "$GOMODCACHE:$GOMODCACHE"
              environment:
                - "CGO_ENABLED=0"
                - "GOOS=linux"
                - "GOFLAGS=-buildvcs=false"
  - group: ":docker: Docker Image"
    depends_on: "go-build"
    key: "docker-build"
    steps:
      - label: ":docker: docker PR build and scan"
        key: "docker-pr-build"
        cancel_on_build_failing: true
        if: build.branch != "main" && build.tag == null
        commands: |
          #!/bin/bash
          chmod +x bin/${APP_NAME}
        plugins:
          - artifacts#v1.9.4:
              download: "bin/${APP_NAME}"
              step: "gobuild"
          - docker-login#v3.0.0:
              username: openlane-bender
              password-env: SECRET_GHCR_PUBLISH_TOKEN
              server: ghcr.io
          - theopenlane/docker-metadata#v1.0.1:
              images:
                - "${IMAGE_REPO}"
              extra_tags:
                - "${IMAGE_TAG}"
          - theopenlane/container-build#v1.1.1:
              dockerfile: Dockerfile
              push: false
          - equinixmetal-buildkite/trivy#v1.20.0:
              severity: CRITICAL,HIGH
              ignore-unfixed: true
              scanners: misconfig,secret,vuln
      - label: ":docker: docker build and publish"
        key: "docker-build-and-tag"
        cancel_on_build_failing: true
        if: build.tag != null
        commands: |
          #!/bin/bash
          chmod +x bin/${APP_NAME}
        plugins:
          - artifacts#v1.9.4:
              download: "bin/${APP_NAME}"
              step: "gobuild"
          - docker-login#v3.0.0:
              username: openlane-bender
              password-env: SECRET_GHCR_PUBLISH_TOKEN
              server: ghcr.io
          - theopenlane/docker-metadata#v1.0.1:
              images:
                - "${IMAGE_REPO}"
              extra_tags:
                - "${BUILDKITE_TAG}"
                - "latest"
          - theopenlane/container-build#v1.1.1:
              dockerfile: Dockerfile
              push: true
  - group: ":helm: Chart Update"
    depends_on: "docker-build"
    key: "chart-update"
    steps:
      - label: ":rocket: update image tag for release"
        key: "image_tag_automation"
        depends_on: "docker-build-and-tag"
        if: build.tag != null
        plugins:
          - docker#v5.13.0:
              image: "ghcr.io/theopenlane/build-image:latest"
              always-pull: true
              command: ["sh", "-c", "apk add --no-cache bash >/dev/null 2>&1 && bash .buildkite/image-tag-automation.sh"]
              propagate-environment: true
              volumes:
                - "$GOCACHE:$GOCACHE"
                - "$GOMODCACHE:$GOMODCACHE"
              environment:
                - "GITHUB_TOKEN"
                - "GITHUB_SSH_PRIVATE_KEY"
                - "HELM_CHART_REPO"
                - "HELM_CHART_PATH"
                - "BUILDKITE_BUILD_CHECKOUT_PATH=/workdir"
