// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIErrorResponse api error response
//
// swagger:model api.ErrorResponse
type APIErrorResponse struct {

	// error
	// Example: Invalid request body
	Error string `json:"error,omitempty"`

	// success
	// Example: false
	Success bool `json:"success,omitempty"`
}

// Validate validates this api error response
func (m *APIErrorResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api error response based on context it is used
func (m *APIErrorResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIErrorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIErrorResponse) UnmarshalBinary(b []byte) error {
	var res APIErrorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
