// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIHealthResponse api health response
//
// swagger:model api.HealthResponse
type APIHealthResponse struct {

	// service
	// Example: sleuth
	Service string `json:"service,omitempty"`

	// status
	// Example: healthy
	Status string `json:"status,omitempty"`

	// timestamp
	// Example: 2024-01-15T10:30:00Z
	Timestamp string `json:"timestamp,omitempty"`
}

// Validate validates this api health response
func (m *APIHealthResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api health response based on context it is used
func (m *APIHealthResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIHealthResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIHealthResponse) UnmarshalBinary(b []byte) error {
	var res APIHealthResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
