// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIScanRequest api scan request
//
// swagger:model api.ScanRequest
type APIScanRequest struct {

	// domain
	// Example: example.com
	Domain string `json:"domain,omitempty"`

	// email
	// Example: user@example.com
	Email string `json:"email,omitempty"`
}

// Validate validates this api scan request
func (m *APIScanRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api scan request based on context it is used
func (m *APIScanRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIScanRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIScanRequest) UnmarshalBinary(b []byte) error {
	var res APIScanRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
