// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TypesDomainInfo types domain info
//
// swagger:model types.DomainInfo
type TypesDomainInfo struct {

	// domain
	// Example: sub.example.com
	Domain string `json:"domain,omitempty"`

	// sld
	// Example: example
	Sld string `json:"sld,omitempty"`

	// subdomain
	// Example: sub
	Subdomain string `json:"subdomain,omitempty"`

	// tld
	// Example: com
	Tld string `json:"tld,omitempty"`
}

// Validate validates this types domain info
func (m *TypesDomainInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this types domain info based on context it is used
func (m *TypesDomainInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TypesDomainInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TypesDomainInfo) UnmarshalBinary(b []byte) error {
	var res TypesDomainInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
