// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TypesFinding types finding
//
// swagger:model types.Finding
type TypesFinding struct {

	// description
	// Example: Potential CNAME takeover vulnerability
	Description string `json:"description,omitempty"`

	// details
	// Example: CNAME points to unclaimed service
	Details string `json:"details,omitempty"`

	// severity
	// Example: high
	Severity string `json:"severity,omitempty"`

	// type
	// Example: cname_takeover
	Type string `json:"type,omitempty"`
}

// Validate validates this types finding
func (m *TypesFinding) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this types finding based on context it is used
func (m *TypesFinding) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TypesFinding) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TypesFinding) UnmarshalBinary(b []byte) error {
	var res TypesFinding
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
