// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/theopenlane/sleuth/client/models"
)

// PostScanReader is a Reader for the PostScan structure.
type PostScanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostScanReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostScanOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostScanBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewPostScanMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostScanInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /scan] PostScan", response, response.Code())
	}
}

// NewPostScanOK creates a PostScanOK with default headers values
func NewPostScanOK() *PostScanOK {
	return &PostScanOK{}
}

/*
PostScanOK describes a response with status code 200, with default header values.

OK
*/
type PostScanOK struct {
	Payload *models.APIScanResponse
}

// IsSuccess returns true when this post scan o k response has a 2xx status code
func (o *PostScanOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post scan o k response has a 3xx status code
func (o *PostScanOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post scan o k response has a 4xx status code
func (o *PostScanOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post scan o k response has a 5xx status code
func (o *PostScanOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post scan o k response a status code equal to that given
func (o *PostScanOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post scan o k response
func (o *PostScanOK) Code() int {
	return 200
}

func (o *PostScanOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /scan][%d] postScanOK %s", 200, payload)
}

func (o *PostScanOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /scan][%d] postScanOK %s", 200, payload)
}

func (o *PostScanOK) GetPayload() *models.APIScanResponse {
	return o.Payload
}

func (o *PostScanOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIScanResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostScanBadRequest creates a PostScanBadRequest with default headers values
func NewPostScanBadRequest() *PostScanBadRequest {
	return &PostScanBadRequest{}
}

/*
PostScanBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostScanBadRequest struct {
	Payload *models.APIErrorResponse
}

// IsSuccess returns true when this post scan bad request response has a 2xx status code
func (o *PostScanBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post scan bad request response has a 3xx status code
func (o *PostScanBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post scan bad request response has a 4xx status code
func (o *PostScanBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post scan bad request response has a 5xx status code
func (o *PostScanBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post scan bad request response a status code equal to that given
func (o *PostScanBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post scan bad request response
func (o *PostScanBadRequest) Code() int {
	return 400
}

func (o *PostScanBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /scan][%d] postScanBadRequest %s", 400, payload)
}

func (o *PostScanBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /scan][%d] postScanBadRequest %s", 400, payload)
}

func (o *PostScanBadRequest) GetPayload() *models.APIErrorResponse {
	return o.Payload
}

func (o *PostScanBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostScanMethodNotAllowed creates a PostScanMethodNotAllowed with default headers values
func NewPostScanMethodNotAllowed() *PostScanMethodNotAllowed {
	return &PostScanMethodNotAllowed{}
}

/*
PostScanMethodNotAllowed describes a response with status code 405, with default header values.

Method Not Allowed
*/
type PostScanMethodNotAllowed struct {
	Payload *models.APIErrorResponse
}

// IsSuccess returns true when this post scan method not allowed response has a 2xx status code
func (o *PostScanMethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post scan method not allowed response has a 3xx status code
func (o *PostScanMethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post scan method not allowed response has a 4xx status code
func (o *PostScanMethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this post scan method not allowed response has a 5xx status code
func (o *PostScanMethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this post scan method not allowed response a status code equal to that given
func (o *PostScanMethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

// Code gets the status code for the post scan method not allowed response
func (o *PostScanMethodNotAllowed) Code() int {
	return 405
}

func (o *PostScanMethodNotAllowed) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /scan][%d] postScanMethodNotAllowed %s", 405, payload)
}

func (o *PostScanMethodNotAllowed) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /scan][%d] postScanMethodNotAllowed %s", 405, payload)
}

func (o *PostScanMethodNotAllowed) GetPayload() *models.APIErrorResponse {
	return o.Payload
}

func (o *PostScanMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostScanInternalServerError creates a PostScanInternalServerError with default headers values
func NewPostScanInternalServerError() *PostScanInternalServerError {
	return &PostScanInternalServerError{}
}

/*
PostScanInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostScanInternalServerError struct {
	Payload *models.APIErrorResponse
}

// IsSuccess returns true when this post scan internal server error response has a 2xx status code
func (o *PostScanInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post scan internal server error response has a 3xx status code
func (o *PostScanInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post scan internal server error response has a 4xx status code
func (o *PostScanInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post scan internal server error response has a 5xx status code
func (o *PostScanInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post scan internal server error response a status code equal to that given
func (o *PostScanInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post scan internal server error response
func (o *PostScanInternalServerError) Code() int {
	return 500
}

func (o *PostScanInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /scan][%d] postScanInternalServerError %s", 500, payload)
}

func (o *PostScanInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /scan][%d] postScanInternalServerError %s", 500, payload)
}

func (o *PostScanInternalServerError) GetPayload() *models.APIErrorResponse {
	return o.Payload
}

func (o *PostScanInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
