// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Openlane Support",
            "url": "https://github.com/theopenlane/sleuth",
            "email": "support@openlane.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns the health status of the Sleuth service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    }
                }
            }
        },
        "/scan": {
            "post": {
                "description": "Performs comprehensive security and technology analysis on a domain\nAccepts either an email address (domain extracted) or direct domain",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scan"
                ],
                "summary": "Scan domain",
                "parameters": [
                    {
                        "description": "Scan request containing email or domain",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ScanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ScanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid request body"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "api.HealthResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string",
                    "example": "sleuth"
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                }
            }
        },
        "api.ScanRequest": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string",
                    "example": "example.com"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                }
            }
        },
        "api.ScanResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.ScanResult"
                },
                "error": {
                    "type": "string",
                    "example": "Invalid domain format"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "types.CheckResult": {
            "type": "object",
            "properties": {
                "check_name": {
                    "type": "string",
                    "example": "dns_analysis"
                },
                "error": {
                    "type": "string",
                    "example": "DNS lookup failed"
                },
                "findings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Finding"
                    }
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "status": {
                    "type": "string",
                    "example": "pass"
                }
            }
        },
        "types.DomainInfo": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string",
                    "example": "sub.example.com"
                },
                "sld": {
                    "type": "string",
                    "example": "example"
                },
                "subdomain": {
                    "type": "string",
                    "example": "sub"
                },
                "tld": {
                    "type": "string",
                    "example": "com"
                }
            }
        },
        "types.Finding": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Potential CNAME takeover vulnerability"
                },
                "details": {
                    "type": "string",
                    "example": "CNAME points to unclaimed service"
                },
                "severity": {
                    "type": "string",
                    "example": "high"
                },
                "type": {
                    "type": "string",
                    "example": "cname_takeover"
                }
            }
        },
        "types.ScanResult": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string",
                    "example": "example.com"
                },
                "domain_info": {
                    "$ref": "#/definitions/types.DomainInfo"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.CheckResult"
                    }
                },
                "scanned_at": {
                    "type": "string",
                    "example": "1705316400"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "Sleuth API",
	Description:      "Domain analysis sidecar service for security and technology discovery",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
